language: rust
rust:
  - stable
before_script:
  - cargo install cargo-lichking
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup install nightly --profile minimal
  - rustup override set --path python nightly
  - pip3 install maturin
install:
  []
script:
  - make test
  - make build_py
cache:
  - cargo
  - pip