name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev python3-venv

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install cargo-deny
        run: cargo install --force --version 0.6.8 cargo-deny --locked

      - name: Run tests
        run: make test

      - name: Run CPython wrapper tests
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install --upgrade pip
          pip3 install maturin
          make test_py
