name: CI

on:
  pull_request:
  push: # required for actions/cache to work
    branches:
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v2
      - name: Cache
        id: rust-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml', '.github/workflows/*.yml', 'rust-toolchain') }}

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Install cargo-deny
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: rustup run --install 1.74 cargo install --force --version 0.14.3 cargo-deny --locked

      - name: Run tests
        run: make test

      - name: Run tests (no-std)
        run: cargo test --no-default-features

      - name: Run CPython wrapper tests
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install --upgrade pip
          pip3 install maturin
          make test_py
